db_host: localhost
snort_log_path: /var/log/snort/alert

db:
  host: localhost
  port: 3306
  user: root
  password: password
  database: sdn_db

snort:
  alert_path: /var/log/snort/alert

floodlight:
  host: 127.0.0.1
  port: 8080
  base_api: /wm/staticflowentrypusher/json
