#db_host: localhost
#snort_log_path: /var/log/snort/alert

db:
  host: localhost
  port: 3306
  user: diego
  password: Ubuntu2025*
  database: db_sdn

snort:
  alert_path: /var/log/snort/alert

floodlight:
  host: 127.0.0.1
  port: 8080
  base_api: /wm/staticflowentrypusher/json

freeradius:
  host: 127.0.0.1
  port: 1812
  secret: testing123
  dictionary_path: config/dictionary

